export const CMS_BASE_URL = 'https://raw.githubusercontent.com/easyfinance-learning/EasyFinanceLibrary/main/';

export const EBOOKS = [
  {
    id: '1',
    title: '50-30-20 Rule',
    pages: 5,
    tag: 'Featured',
    level: 'Beginner',
    bg: '#EAF5EE',
    accent: '#135E2D',
    emoji: '💰',
    description: 'A Simple Guide to Managing Your Money Without Stress by Abhijit Khare.',
    author: 'Abhijit Khare',
    readTime: '20 mins',
    coverUrl: 'https://raw.githubusercontent.com/easyfinance-learning/EasyFinanceLibrary/main/cover_50_30_20.png',
    content: `Chapter 1: Why Money Matters\n\nMoney is not everything, but it affects everything. From the food you eat to the dreams you chase, financial health plays a central role in your quality of life.\n\nIn this book, we will break down complex financial concepts into simple, actionable steps that anyone can follow — regardless of income or background.\n\nChapter 2: The 50-30-20 Rule\n\nOne of the simplest budgeting frameworks is the 50-30-20 rule:\n\n• 50% of your income goes to Needs (rent, food, bills)\n• 30% goes to Wants (dining out, entertainment)\n• 20% goes to Savings and Investments\n\nThis rule gives you a strong foundation to build your financial life.\n\nChapter 3: Emergency Fund\n\nBefore you invest, build an emergency fund. This should cover 3 to 6 months of your monthly expenses.\n\nKeep this money in a liquid savings account — not in stocks or mutual funds — so you can access it immediately when needed.\n\nChapter 4: The Power of Compounding\n\nAlbert Einstein called compound interest the eighth wonder of the world. When your money earns returns, and those returns also earn returns, your wealth grows exponentially over time.\n\nStart early. Even small amounts invested consistently can grow into significant wealth over 20-30 years.\n\nChapter 5: Getting Started\n\nThe best time to start was yesterday. The next best time is today. Open a savings account, set up a SIP, and take your first step toward financial freedom.`,
  },
  {
    id: '2',
    title: 'Mutual Funds 101',
    pages: 120,
    tag: 'Popular',
    level: 'Beginner',
    bg: '#E8F5E9',
    accent: '#4CAF50',
    emoji: '📊',
    description: 'Everything you need to know about mutual funds — types, how to choose, SIP vs lump sum, and how to start investing today.',
    author: 'Easy Finance',
    readTime: '3 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400',
    contentUrl: `${CMS_BASE_URL}content/mutual_funds_101.txt`,
    content: `Chapter 1: What is a Mutual Fund?\n\nA mutual fund is a pool of money collected from many investors, managed by a professional fund manager, and invested in stocks, bonds, or other assets.\n\nThink of it as a group of people coming together to invest collectively — giving even small investors access to a diversified portfolio.\n\nChapter 2: Types of Mutual Funds\n\n• Equity Funds — Invest in stocks. High risk, high return.\n• Debt Funds — Invest in bonds. Lower risk, stable returns.\n• Hybrid Funds — Mix of equity and debt.\n• Index Funds — Track a market index like Nifty 50.\n\nChapter 3: SIP vs Lump Sum\n\nSIP (Systematic Investment Plan) means investing a fixed amount every month. It is ideal for salaried individuals and helps average out market ups and downs.\n\nLump Sum means investing a large amount at once. Best when markets are at a low point.\n\nFor beginners, SIP is almost always the better choice.\n\nChapter 4: How to Choose a Fund\n\nLook at: past performance (5-10 years), expense ratio, fund manager track record, and your own risk appetite.\n\nDon't chase last year's top performer. Consistency matters more than short-term highs.\n\nChapter 5: Starting Your First SIP\n\nYou can start a SIP with as little as ₹500 per month. Choose a reputed platform, complete your KYC, and set up an auto-debit. That's it — you're an investor!`,
  },
  {
    id: '3',
    title: 'SIP Mastery',
    pages: 98,
    tag: 'New',
    level: 'Advanced',
    bg: '#EDE7F6',
    accent: '#4527A0',
    emoji: '📈',
    description: 'Master the art of SIP investing — step-up SIPs, best funds to choose, common mistakes, and how to build a crore-rupee portfolio.',
    author: 'Easy Finance',
    readTime: '2.5 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    contentUrl: `${CMS_BASE_URL}content/sip_mastery.txt`,
    content: `Chapter 1: Beyond Basic SIP\n\nYou already know what a SIP is. This book is about mastering it. We explore advanced strategies that can dramatically improve your long-term returns.\n\nChapter 2: Step-Up SIP\n\nA Step-Up SIP means increasing your monthly SIP amount every year — typically by 10-15%. This mirrors your income growth and dramatically boosts your final corpus.\n\nExample: A ₹5,000 SIP with 10% annual step-up over 20 years creates nearly 3x more wealth than a flat ₹5,000 SIP.\n\nChapter 3: SIP Timing Myths\n\nMany investors worry about which date to start their SIP. Research shows the date matters very little over the long term. The most important thing is to start — and stay consistent.\n\nChapter 4: Pausing vs Stopping\n\nIf you face financial difficulty, pause your SIP — don't stop it permanently. Most platforms allow you to pause for 1-3 months. Stopping and restarting breaks the compounding chain.\n\nChapter 5: Building a ₹1 Crore Portfolio\n\nWith a ₹10,000 monthly SIP in a fund averaging 12% annual returns, you can reach ₹1 crore in approximately 20 years. Start at 25, retire wealthy at 45.`,
  },
  {
    id: '4',
    title: 'Tax Saving Guide',
    pages: 80,
    tag: 'Hot',
    level: 'Beginner',
    bg: '#FCE4EC',
    accent: '#C62828',
    emoji: '🧾',
    description: 'Save maximum tax legally in 2025. Covers Section 80C, ELSS, NPS, HRA, and all deductions you must know before filing your ITR.',
    author: 'Easy Finance',
    readTime: '2 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400',
    contentUrl: `${CMS_BASE_URL}content/tax_saving_guide.txt`,
    content: `Chapter 1: Why Tax Planning Matters\n\nPaying more tax than required is one of the most common financial mistakes. With proper planning, you can legally save thousands every year.\n\nChapter 2: Section 80C — ₹1.5 Lakh Deduction\n\nThe most popular tax-saving section. Eligible investments include:\n\n• ELSS Mutual Funds (best returns + lowest lock-in of 3 years)\n• PPF (safe, 15-year lock-in)\n• Life Insurance Premiums\n• EPF contributions\n• NSC, Tax-saving FDs\n\nChapter 3: ELSS — Best 80C Option\n\nEquity Linked Savings Scheme (ELSS) funds offer the dual benefit of tax saving under 80C and potential equity returns of 12-15% over the long term. They have the shortest lock-in of all 80C options.\n\nChapter 4: NPS for Extra ₹50,000 Deduction\n\nUnder Section 80CCD(1B), you get an additional ₹50,000 deduction for NPS contributions — over and above the ₹1.5 lakh 80C limit.\n\nChapter 5: Other Deductions\n\n• 80D: Health insurance premiums\n• HRA: House Rent Allowance\n• 80E: Education loan interest\n• 80G: Donations to charity\n\nDon't leave money on the table. Use every deduction you're entitled to.`,
  },
  {
    id: '5',
    title: 'Stock Market 101',
    pages: 135,
    tag: 'Popular',
    level: 'Beginner',
    bg: '#E3F2FD',
    accent: '#1565C0',
    emoji: '📉',
    description: 'Understand how the stock market works, how to read charts, what BSE and NSE are, and how to make your first stock investment safely.',
    author: 'Easy Finance',
    readTime: '3.5 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400',
    contentUrl: `${CMS_BASE_URL}content/stock_market_101.txt`,
    content: `Chapter 1: What is the Stock Market?\n\nWhen you buy a share of a company, you become a part-owner of that company. The stock market is simply a marketplace where these shares are bought and sold.\n\nIn India, the two main exchanges are BSE (Bombay Stock Exchange) and NSE (National Stock Exchange).\n\nChapter 2: How Prices Move\n\nStock prices move based on supply and demand. When more people want to buy a stock than sell it, the price rises. When more want to sell, the price falls.\n\nUnderlying this are company fundamentals — earnings, growth, management quality, and industry trends.\n\nChapter 3: Key Terms You Must Know\n\n• Sensex: Top 30 companies on BSE\n• Nifty 50: Top 50 companies on NSE\n• Bull Market: Rising market\n• Bear Market: Falling market\n• Dividend: Share of company profits paid to shareholders\n\nChapter 4: Direct Stocks vs Mutual Funds\n\nFor beginners, mutual funds are safer than picking individual stocks. Direct stock investing requires research, time, and emotional discipline.\n\nStart with index funds. Graduate to direct stocks only after you understand fundamentals.\n\nChapter 5: Opening a Demat Account\n\nTo buy stocks, you need a Demat account linked to your bank. Popular platforms include Zerodha, Groww, and Upstox. KYC takes 10-15 minutes online.`,
  },
  {
    id: '6',
    title: 'Retire Early (FIRE)',
    pages: 110,
    tag: 'Trending',
    level: 'Advanced',
    bg: '#FFF9C4',
    accent: '#F57F17',
    emoji: '🔥',
    description: 'The complete FIRE (Financial Independence, Retire Early) guide for Indians — how much you need, how to get there, and what life looks like after.',
    author: 'Easy Finance',
    readTime: '3 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
    contentUrl: `${CMS_BASE_URL}content/retire_early.txt`,
    content: `Chapter 1: What is FIRE?\n\nFIRE stands for Financial Independence, Retire Early. It is a movement built around aggressive saving and investing to achieve freedom from mandatory work decades before the traditional retirement age.\n\nChapter 2: The 25x Rule\n\nTo retire early, you need a corpus of 25 times your annual expenses. This is based on the 4% safe withdrawal rate — you can withdraw 4% of your portfolio every year without running out of money.\n\nExample: If you spend ₹10 lakh per year, you need ₹2.5 crore to retire.\n\nChapter 3: Types of FIRE\n\n• Lean FIRE: Retire with a minimal lifestyle\n• Fat FIRE: Retire with a comfortable, even luxurious lifestyle\n• Barista FIRE: Semi-retire with part-time work covering some expenses\n\nChapter 4: The Indian FIRE Context\n\nIndia offers unique FIRE advantages — lower cost of living, family support systems, and strong equity market returns. A ₹5 crore corpus can support a very comfortable retirement in most Indian cities.\n\nChapter 5: Getting Started\n\nCalculate your FIRE number. Increase your savings rate. Invest aggressively in equity. Track your progress annually. The journey to FIRE starts with a single SIP.`,
  },
  {
    id: '7',
    title: 'Budget Like a Pro',
    pages: 75,
    tag: 'New',
    level: 'Beginner',
    bg: '#E0F7FA',
    accent: '#00695C',
    emoji: '🗂️',
    description: 'Master budgeting with proven frameworks — zero-based budgeting, envelope method, and digital tools to track every rupee.',
    author: 'Easy Finance',
    readTime: '2 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?w=400',
    contentUrl: `${CMS_BASE_URL}content/budget_like_a_pro.txt`,
    content: `Chapter 1: Why Most Budgets Fail\n\nMost people make budgets and abandon them within weeks. The reason is not lack of discipline — it is using the wrong system.\n\nA good budget should be simple, flexible, and honest about your actual spending habits.\n\nChapter 2: Zero-Based Budgeting\n\nIn zero-based budgeting, every rupee of your income is assigned a job. Income minus all allocations equals zero. This doesn't mean you spend everything — savings and investments are also allocations.\n\nChapter 3: The Envelope Method\n\nDivide your cash into envelopes for different categories — groceries, entertainment, transport, etc. When an envelope is empty, spending in that category stops for the month.\n\nThis works brilliantly for people who overspend on specific categories.\n\nChapter 4: Digital Budgeting Tools\n\nApps like Walnut, Money Manager, and even a simple Excel sheet can transform your budgeting. The best tool is the one you will actually use consistently.\n\nChapter 5: Review and Adjust\n\nReview your budget every month. Life changes — so should your budget. The goal is progress, not perfection.`,
  },
  {
    id: '8',
    title: 'Insurance Essentials',
    pages: 90,
    tag: 'Hot',
    level: 'Advanced',
    bg: '#F3E5F5',
    accent: '#6A1B9A',
    emoji: '🛡️',
    description: 'A balanced, no-hype guide to insurance for Indian families — term life insurance, health insurance, critical illness riders, and common mistakes.',
    author: 'Easy Finance',
    readTime: '2.5 hrs',
    coverUrl: 'https://images.unsplash.com/photo-1516245834210-c4c142787335?w=400',
    contentUrl: `${CMS_BASE_URL}content/insurance_essentials.txt`,
    content: `Chapter 1: Why Insurance is Foundation\n\nMany people treat insurance as an investment. This is a huge mistake. Insurance is pure protection — a shield for your assets and your family.\n\nChapter 2: Term Life Insurance\n\nIf you have dependents, you need a pure term life insurance plan. The cover should be at least 10-15 times your annual income. Avoid endowment or money-back policies.\n\nChapter 3: Health Insurance\n\nMedical inflation in India is rising at 15% annually. A single hospitalisation can wipe out your savings. Buy a family floater health plan of at least ₹5-10 lakhs.\n\nChapter 4: Crucial Riders\n\nConsider adding critical illness and accidental disability riders to your term plan for extra protection.\n\nChapter 5: Bottom Line\n\nBuy insurance to cover risk, and invest in mutual funds to build wealth. Keep them separate.`,
  },
  {
    id: '9',
    title: 'Why Money Management Matters',
    pages: 2,
    tag: 'New',
    level: 'Beginner',
    bg: '#E8F5E9',
    accent: '#4CAF50',
    emoji: '📖',
    description: 'Learn the importance of budgeting, saving, and investing early with real-life case studies.',
    author: 'Abhijit Khare',
    readTime: '15 mins',
    coverUrl: 'https://raw.githubusercontent.com/easyfinance-learning/EasyFinanceLibrary/main/chapter_1_bank_statement.png',
    content: `Table of Contents\n\n1. Why Money Management Matters\n2. Understanding the 50-30-20 Rule\n3. How to Divide Your Income Correctly\n4. Real-Life Examples of the 50-30-20 Rule\n5. Common Mistakes and How to Avoid Them\n6. Your 30-Day Action Plan for Financial Success\n\nChapter 1: Why Money Management Matters\n\n![Rajesh reviewing his bank statement at home](https://raw.githubusercontent.com/easyfinance-learning/EasyFinanceLibrary/main/chapter_1_bank_statement.png)\n\n## Real-Life Situation\nRajesh is 45 years old and works as a senior manager in a private company. He earns more than ₹1,20,000 per month. He owns a car, has a home loan, takes family vacations, and appears financially successful from the outside.\n\nBut one day, a medical emergency in the family changes everything.\n\nWhen he reviews his finances, he discovers a harsh reality:\n• Very little emergency savings\n• Multiple loan EMIs\n• Credit card outstanding balances\n• No proper retirement planning\n• Investments started too late\n\nFor years, Rajesh believed that earning a good income was enough. Unfortunately, he never paid attention to managing his money.\n\nHis story is not unique.\n\nAcross India, thousands of people work hard, earn decent incomes, and provide for their families. Yet many still experience financial stress because they never learn one important skill:\nMoney management.\n\n## Introduction\nMost of us spend years learning how to earn money.\n\nWe study, build careers, gain experience, and work hard to increase our income. But very few people are taught how to manage the money they earn.\n\nSchools rarely teach personal finance.\nColleges rarely teach budgeting.\nMany families avoid discussing money openly.\n\nAs a result, people enter adulthood with little understanding of saving, investing, debt management, or financial planning.\n\nThe consequences often become visible later in life.\n\nMany people reach their forties and realize they have worked for decades but have very little to show for it financially. They may have a good salary, but they also have loans, financial stress, and limited savings.\n\nThis chapter is not about becoming rich overnight.\n\nIt is about understanding why managing money matters and why the decisions you make today can shape your financial future for years to come.\n\n## Main Concepts\n\n### Earning More Does Not Automatically Create Wealth\nOne of the biggest misconceptions about money is that higher income automatically leads to financial success.\n\nIn reality, income and wealth are not the same thing.\n\nConsider two individuals:\n\n**Person A**\n• Monthly income: ₹50,000\n• Saves regularly\n• Avoids unnecessary debt\n• Invests consistently\n\n**Person B**\n• Monthly income: ₹1,50,000\n• Spends most of the income\n• Uses credit cards excessively\n• Has multiple loans\n• Rarely saves or invests\n\nAfter ten years, **Person A** may be in a stronger financial position despite earning less.\n\nWhy?\n\nBecause wealth is built through habits, not income alone.\n\nFinancial success is not determined only by what comes into your bank account. It is determined by what you do with the money after it arrives.\n\n### Money Management Is About Habits\nMany people believe their financial problems will disappear once they start earning more.\n\nUnfortunately, that is not always true.\n\nWhen income increases, spending often increases as well.\n\nA bigger salary may lead to:\n• A larger house\n• A more expensive car\n• Premium gadgets\n• Frequent dining out\n• Lifestyle upgrades\n\nWithout discipline, expenses rise at the same pace as income.\n\nGood money management begins with habits such as:\n• Tracking expenses\n• Saving regularly\n• Avoiding unnecessary debt\n• Planning before spending\n• Investing for long-term goals\n\nSmall habits repeated consistently often create better results than occasional large financial decisions.\n\n### The Cost of Ignoring Money\nIgnoring money management does not create problems immediately.\n\nThat is what makes it dangerous.\n\nA person may spend carelessly for years without noticing any major consequences.\n\nHowever, financial mistakes often accumulate silently.\n\nExamples include:\n• Delaying investments\n• Taking unnecessary loans\n• Depending heavily on credit cards\n• Living without an emergency fund\n• Ignoring retirement planning\n\nOver time, these decisions create financial pressure.\n\nMany people discover the impact only when they face:\n• A medical emergency\n• Job loss\n• Business slowdown\n• Children's education expenses\n• Retirement planning challenges\n\nMoney problems rarely appear overnight. They usually develop slowly over many years.\n\n### Social Pressure and Financial Decisions\nOne of the most overlooked financial challenges in India is social pressure.\n\nMany people spend money not because they need to, but because they feel they should.\n\nExamples include:\n• Buying expensive smartphones on EMI\n• Hosting lavish celebrations`,
  },
];

export const NEWSLETTERS = [
  {
    id: '1',
    title: 'Finance Weekly',
    issue: 'Issue #24',
    date: 'Jun 2025',
    topic: 'Mutual Funds',
    bg: '#E3F2FD',
    accent: '#65D34A',
    emoji: '📊',
    hot: true,
    description: 'This week: Best mutual funds for 2025, SIP vs lump sum debate settled, and why index funds are winning.',
    coverUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_24.txt`,
    content: `FINANCE WEEKLY — Issue #24\nJune 2025\n\n─────────────────────────\n📊 TOP STORY: Best Mutual Funds for 2025\n─────────────────────────\n\nAs we enter the second half of 2025, here are the top-performing mutual fund categories:\n\n1. Flexi-cap Funds — Offering the best of large, mid, and small cap exposure with dynamic allocation.\n\n2. Index Funds — Nifty 50 and Nifty Next 50 index funds continue to beat most active large-cap funds after expense ratios.\n\n3. Mid-cap Funds — For investors with a 7+ year horizon, mid-cap funds are delivering strong alpha.\n\n─────────────────────────\n💡 INSIGHT: SIP vs Lump Sum\n─────────────────────────\n\nA common debate among investors. The data is clear: over a 10-year period, the difference in returns between SIP and lump sum in equity funds is minimal — around 0.5 to 1%.\n\nThe real advantage of SIP is behavioural — it removes the temptation to time the market and ensures consistent investing.\n\n─────────────────────────\n📈 MARKET UPDATE\n─────────────────────────\n\nNifty 50 touched a new all-time high this week, crossing the 24,500 mark. FII inflows have been strong, driven by expectations of a US Fed rate cut.\n\nDomestic mutual fund SIP contributions crossed ₹21,000 crore in May 2025 — a new record.\n\n─────────────────────────\n🎯 THIS WEEK'S TIP\n─────────────────────────\n\nReview your mutual fund portfolio once every 6 months. Don't review it every day — that leads to panic selling at the worst times.\n\nStay invested. Stay consistent. See you next week!`,
  },
  {
    id: '2',
    title: 'Market Pulse',
    issue: 'Issue #23',
    date: 'May 2025',
    topic: 'Stock Market',
    bg: '#F3E5F5',
    accent: '#6A1B9A',
    emoji: '📈',
    hot: false,
    description: 'Market recap: Sensex hits new highs, IT sector rebounds, and what the election results mean for your portfolio.',
    coverUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_23.txt`,
    content: `MARKET PULSE — Issue #23\nMay 2025\n\n─────────────────────────\n📈 SENSEX HITS NEW HIGH\n─────────────────────────\n\nThe BSE Sensex crossed 80,000 for the first time this month, driven by strong corporate earnings and positive global cues.\n\nKey drivers:\n• Strong Q4 FY25 earnings from banking and IT sectors\n• Declining crude oil prices\n• Positive FII flows of ₹15,000+ crore in May\n\n─────────────────────────\n💻 IT SECTOR REBOUNDS\n─────────────────────────\n\nAfter a difficult 2024, the IT sector is showing signs of recovery. TCS, Infosys, and Wipro all reported better-than-expected deal wins in Q4.\n\nAnalysts are cautiously optimistic, with a 12-15% upside expected in large-cap IT stocks over the next 12 months.\n\n─────────────────────────\n🗳️ WHAT ELECTIONS MEAN FOR MARKETS\n─────────────────────────\n\nHistorically, Indian markets have delivered positive returns in the 12 months following general elections, regardless of which party wins.\n\nThe real market driver is economic policy continuity and corporate earnings growth — not political outcomes.\n\n─────────────────────────\n🎯 INVESTOR TAKEAWAY\n─────────────────────────\n\nDon't make investment decisions based on short-term market news. Your SIP doesn't care which party won — it just keeps compounding.`,
  },
  {
    id: '3',
    title: 'Money Matters',
    issue: 'Issue #22',
    date: 'May 2025',
    topic: 'Personal Finance',
    bg: '#E0F7FA',
    accent: '#00695C',
    emoji: '💸',
    hot: false,
    description: 'Personal finance fundamentals: Building your first budget, emergency fund basics, and the one habit that changes everything.',
    coverUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_22.txt`,
    content: `MONEY MATTERS — Issue #22\nMay 2025\n\n─────────────────────────\n💸 BUILDING YOUR FIRST BUDGET\n─────────────────────────\n\nIf you've never budgeted before, start with just three categories:\n\n1. Fixed expenses (rent, EMIs, insurance)\n2. Variable expenses (food, transport, entertainment)\n3. Savings and investments\n\nTrack for one month without judging yourself. Just observe where your money goes. That awareness alone is transformative.\n\n─────────────────────────\n🛡️ EMERGENCY FUND: YOUR FINANCIAL SHIELD\n─────────────────────────\n\nAn emergency fund is not an investment — it is insurance against life's uncertainties.\n\nTarget: 3-6 months of expenses in a liquid savings account or liquid mutual fund.\n\nStart with a ₹10,000 target. Then ₹50,000. Then 3 months. Small milestones build momentum.\n\n─────────────────────────\n⚡ THE ONE HABIT THAT CHANGES EVERYTHING\n─────────────────────────\n\nPay yourself first.\n\nAs soon as your salary arrives, transfer your savings amount immediately — before paying any bills, before any discretionary spending.\n\nAutomate it. Make it non-negotiable. This single habit, maintained consistently, creates more wealth than any investment strategy.\n\n─────────────────────────\n🎯 ACTION STEP THIS WEEK\n─────────────────────────\n\nSet up one automatic transfer — even ₹1,000 — to a savings account or SIP on your salary date. Do it today.`,
  },
  {
    id: '4',
    title: 'Tax Talk',
    issue: 'Issue #21',
    date: 'Apr 2025',
    topic: 'Tax Planning',
    bg: '#FCE4EC',
    accent: '#C62828',
    emoji: '🧾',
    hot: false,
    description: 'ITR filing season guide: Documents you need, deductions you are missing, and how to file your return in under 30 minutes.',
    coverUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_21.txt`,
    content: `TAX TALK — Issue #21\nApril 2025\n\n─────────────────────────\n🧾 ITR FILING SEASON IS HERE\n─────────────────────────\n\nThe due date for filing ITR for FY 2024-25 is July 31, 2025. Don't wait until the last minute — file early to avoid errors and get your refund faster.\n\n─────────────────────────\n📋 DOCUMENTS CHECKLIST\n─────────────────────────\n\nBefore you start filing, keep these ready:\n\n• Form 16 from your employer\n• Bank statements for all accounts\n• Investment proofs (ELSS, PPF, LIC receipts)\n• Home loan interest certificate (if applicable)\n• Form 26AS (tax credit statement)\n• AIS (Annual Information Statement)\n\n─────────────────────────\n💡 DEDUCTIONS MOST PEOPLE MISS\n─────────────────────────\n\n1. 80D — Health insurance premium for parents (up to ₹50,000 extra)\n2. 80E — Education loan interest (no upper limit)\n3. 80G — Donations to registered charities\n4. 80TTA — Interest on savings account (up to ₹10,000)\n\n─────────────────────────\n⚡ FILE IN 30 MINUTES\n─────────────────────────\n\nUse the Income Tax e-filing portal (incometax.gov.in). Most salaried individuals can use the pre-filled ITR-1 form. Verify using Aadhaar OTP. Done!\n\nIf your taxes are complex, consult a CA — the fee is tax-deductible.`,
  },
  {
    id: '5',
    title: 'SIP Stories',
    issue: 'Issue #20',
    date: 'Apr 2025',
    topic: 'SIP & Investing',
    bg: '#FFF3E0',
    accent: '#FF6F00',
    emoji: '💰',
    hot: true,
    description: 'Real SIP success stories, the step-up SIP calculator breakdown, and why missing just 3 SIPs can hurt your corpus significantly.',
    coverUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_20.txt`,
    content: `SIP STORIES — Issue #20\nApril 2025\n\n─────────────────────────\n💰 REAL SIP SUCCESS STORY\n─────────────────────────\n\nMeet Ramesh, a 28-year-old teacher from Pune who started a ₹3,000 monthly SIP in 2015. Ten years later, his corpus stands at ₹7.2 lakh against an investment of ₹3.6 lakh — a 2x return with zero stress and zero active management.\n\nHis secret? He never stopped. Not during COVID. Not during market crashes. Not when his friends told him to "wait for the right time."\n\n─────────────────────────\n📊 STEP-UP SIP: THE NUMBERS\n─────────────────────────\n\nFlat ₹5,000 SIP for 20 years @ 12% = ₹49.9 lakh\nStep-up ₹5,000 SIP (+10% per year) for 20 years @ 12% = ₹1.08 crore\n\nSame starting amount. Twice the result. Just by increasing your SIP by 10% each year.\n\n─────────────────────────\n⚠️ MISSING SIPS: THE REAL COST\n─────────────────────────\n\nMissing just 3 SIPs in a year might seem harmless. Over 20 years, consistently missing 3 SIPs annually can reduce your final corpus by ₹8-12 lakh.\n\nSet up auto-debit. Remove the human element.\n\n─────────────────────────\n🎯 THIS MONTH'S CHALLENGE\n─────────────────────────\n\nIncrease your existing SIP by just ₹500 this month. Small steps. Big results.`,
  },
  {
    id: '6',
    title: 'Retire Smart',
    issue: 'Issue #19',
    date: 'Mar 2025',
    topic: 'Retirement',
    bg: '#E8F5E9',
    accent: '#2E7D32',
    emoji: '🏖️',
    hot: false,
    description: 'Retirement planning for every age: Your 20s, 30s, 40s, and 50s guide to building a retirement corpus that lasts.',
    coverUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_19.txt`,
    content: `RETIRE SMART — Issue #19\nMarch 2025\n\n─────────────────────────\n🏖️ RETIREMENT PLANNING BY AGE\n─────────────────────────\n\nIN YOUR 20s:\nTime is your biggest asset. Invest aggressively in equity. Even ₹2,000 per month started at 22 can create ₹1 crore by 55.\n\nFocus on: Starting your SIP, building emergency fund, getting health insurance.\n\nIN YOUR 30s:\nIncome is higher but so are responsibilities. Increase SIP amounts. Add term insurance. Consider NPS for retirement corpus.\n\nFocus on: Maximising 80C, buying term insurance, stepping up SIPs.\n\nIN YOUR 40s:\nPeak earning years. Maximise investments. Shift slightly toward hybrid funds. Clear high-interest debt.\n\nFocus on: Debt-free by 50, children's education fund, reviewing retirement corpus progress.\n\nIN YOUR 50s:\nConservative shift. Move 30-40% to debt funds. Keep 60% in equity for growth. Plan withdrawal strategy.\n\nFocus on: Portfolio rebalancing, health insurance upgrade, creating passive income streams.\n\n─────────────────────────\n🔢 HOW MUCH DO YOU NEED?\n─────────────────────────\n\nRule of thumb: 25x your annual expenses at retirement.\n\nIf you'll spend ₹8 lakh/year in retirement → you need ₹2 crore corpus.\n\nFactor in inflation. ₹8 lakh today may be ₹20 lakh in 20 years.`,
  },
  {
    id: '7',
    title: 'Budget Bytes',
    issue: 'Issue #18',
    date: 'Mar 2025',
    topic: 'Budgeting',
    bg: '#FFF9C4',
    accent: '#F57F17',
    emoji: '🗂️',
    hot: false,
    description: 'Practical budgeting tips for young professionals: Dealing with lifestyle inflation, cutting without feeling deprived.',
    coverUrl: 'https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_18.txt`,
    content: `BUDGET BYTES — Issue #18\nMarch 2025\n\n─────────────────────────\n🗂️ LIFESTYLE INFLATION: THE SILENT WEALTH KILLER\n─────────────────────────\n\nLifestyle inflation happens when your spending increases as your income increases — leaving your savings rate unchanged or even declining.\n\nThe average Indian professional gets a 10% salary hike but increases spending by 12%. Net result: falling further behind financially despite earning more.\n\n─────────────────────────\n✂️ CUT WITHOUT FEELING DEPRIVED\n─────────────────────────\n\nThe secret is intentional spending — spending more on what truly matters to you and cutting ruthlessly on what doesn't.\n\nAsk for every expense: "Does this bring me genuine joy or convenience?" If yes, keep it. If it's just habit or social pressure, cut it.\n\nCommon areas where Indians overspend:\n• Eating out (cook 3 more meals a week — save ₹3,000/month)\n• OTT subscriptions (share family plans)\n• Phone upgrades (use your phone one extra year)\n\n─────────────────────────\n💡 THE 48-HOUR RULE\n─────────────────────────\n\nFor any non-essential purchase above ₹1,000, wait 48 hours before buying. You'll find that 60-70% of the time, the urge passes.\n\nThis single habit can save ₹20,000-50,000 per year for most people.\n\n─────────────────────────\n🎯 THIS WEEK'S CHALLENGE\n─────────────────────────\n\nIdentify one recurring expense you can reduce or eliminate. Redirect that money to your SIP.`,
  },
  {
    id: '8',
    title: 'Crypto Corner',
    issue: 'Issue #17',
    date: 'Feb 2025',
    topic: 'Crypto',
    bg: '#EDE7F6',
    accent: '#6A1B9A',
    emoji: '🪙',
    hot: false,
    description: 'Crypto market update, India\'s new crypto tax rules explained simply, and whether Bitcoin belongs in your portfolio.',
    coverUrl: 'https://images.unsplash.com/photo-1516245834210-c4c142787335?w=400',
    contentUrl: `${CMS_BASE_URL}newsletters/issue_17.txt`,
    content: `CRYPTO CORNER — Issue #17\nFebruary 2025\n\n─────────────────────────\n🪙 CRYPTO MARKET UPDATE\n─────────────────────────\n\nBitcoin started 2025 strongly, trading above $95,000 in January before pulling back to the $80,000-85,000 range in February.\n\nEthereum continues to lag Bitcoin, trading at around $3,200 — still 25% below its all-time high.\n\n─────────────────────────\n🇮🇳 INDIA'S CRYPTO TAX — SIMPLIFIED\n─────────────────────────\n\nHere's what you need to know:\n\n• 30% flat tax on all crypto gains (no deductions, no indexation)\n• 1% TDS on transactions above ₹50,000 (₹10,000 for specified persons)\n• Losses in crypto CANNOT be offset against other income\n• Each transaction is a taxable event — even crypto-to-crypto swaps\n\nKeep detailed records of every transaction. Use a crypto tax software or CA who specialises in crypto.\n\n─────────────────────────\n📊 SHOULD BITCOIN BE IN YOUR PORTFOLIO?\n─────────────────────────\n\nArgument FOR: Asymmetric upside, non-correlated asset class, hedge against currency debasement.\n\nArgument AGAINST: 30% tax kills returns, extreme volatility, regulatory uncertainty in India.\n\nOur view: If you want crypto exposure, limit it to 2-5% of total portfolio. Never invest borrowed money. Be prepared to lose it all.\n\n─────────────────────────\n🎯 BOTTOM LINE\n─────────────────────────\n\nFor 99% of Indian investors, equity mutual funds remain a far better wealth-building tool than crypto. Boring wins.`,
  },
];